# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5da5cb252d6d851ef8ce582c3e12a2e2a1aefaac014f36041ac6466d700bfe03ee7bacbbe25edf7d616b3444e6b03466aafe0aa4d561a5f764d8284657100c6

test:
  secret_key_base: 1b5d344ca78d4100d207db21b89fddd135b7e74f01decff4f5382b768e0d76482958202a8a00ced41eeeca3fa739db64045e317e9c8478e522338243a914c0d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
